import * as generate from "./modules/generate.js";
import * as prompts from "./modules/prompts.js";
import * as display from "./modules/display.js";
import * as utility from "./modules/utility.js";
import * as test from "./modules/test.js";
import * as constants from "./modules/constants.js";
import * as formelements from "./modules/formelements.js";
import * as validation from "./modules/validation.js";
import * as autoFill from "./modules/autofill.js";